version: "3.6"

services:
  react:
    environment:
      - MAIN_DOMAIN=localhost.dashboard-ui.pl
      - AUTH_OPENID_PROVIDER=
      - CATALOG_QT_API_URL=http://localhost:8080/
    ports:
      - 9100:9100
