version: "3.6"
services:
  proxy:
    image: nginx
    volumes:
      - ./volumes/nginx-ssl:/etc/nginx/conf.d:ro
      - ./volumes/certs:/etc/nginx/certs:ro
    ports:
      - 443:443
    depends_on:
      - server
      - react

  react:
    environment:
      - CATALOG_QT_API_URL=https://your_domain_name/api  #change your domain name

