version: "3.6"

services:
  db:
    image: catalogqt/db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  server:
    image: catalogqt/server
    depends_on:
      - db
    ports:
      - 8080:8080
      - 8443:8443
 
    environment:
      # - SPRING_CONFIG_LOCATION=file:///catalog_qt_2/server/catalog-ws-server/src/main/resources/application.properties 
      
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb 
      - ./volumes/server-properties:/home/imas/server-properties
      - ./volumes/certs:/home/imas/certs

  updateprocess:
    image: catalogqt/updateprocess
    depends_on:
      - server
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb


  watchdog:
    image: catalogqt/watchdog
    depends_on:
      - server
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/fair4fusion-docker-demo:/docker-entrypoint-properties.d                                                                          