version: "3.6"

services:
  server:
    environment:
      - DISABLE_ACCESS_TOKEN=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/certs:/home/imas/cert
      - ./volumes/server-properties:/home/imas/server-properties

  updateprocess:
    environment:
      - DISABLE_ACCESS_TOKEN=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb

  watchdog:
    environment:
      - DISABLE_ACCESS_TOKEN=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/fair4fusion-docker-demo:/docker-entrypoint-properties.d


