version: "3.6"

services:
  server:
    volumes:
      - imasdb:/home/imas/public/imasdb
      - cert:/home/imas/cert

  updateprocess:
    volumes:
      - imasdb:/home/imas/public/imasdb

  watchdog:
    volumes:
      - imasdb:/home/imas/public/imasdb
      - ./volumes/fair4fusion-production:/docker-entrypoint-properties.d

  react:
    environment:
      - MAIN_DOMAIN=scilla.man.poznan.pl
      - CATALOG_QT_API_URL=https://scilla.man.poznan.pl:8443/
    ports:
      - 80:9100

volumes:
  imasdb:
  cert:
