version: "3.6"

services:
  react:
    image: rhus-71.man.poznan.pl/f4f/dashboard-ui/assets:branch-develop
    environment:
      - LISTEN_PORT=9100
      - S6_READ_ONLY_ROOT=1
      - MAIN_DOMAIN=localhost.dashboard-ui.pl
      - AUTH_OPENID_PROVIDER=
      - CATALOG_QT_API_URL=http://localhost:8080/
    ports:
      - 9100:9100
