version: "3.6"
services:
  proxy:
    image: nginx
    volumes:
      - ./volumes/nginx-ssl-chara:/etc/nginx/conf.d:ro
      - ./volumes/certs:/etc/nginx/certs:ro
    ports:
      - 443:443
    depends_on:
      - server
      - react

  react:
    environment:
      - CATALOG_QT_API_URL=https://chara-47.man.poznan.pl/api
