version: "3.6"

services:
  db:
    image: catalogqt/db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  server:
    image: catalogqt/server
    depends_on:
      - db
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/cert:/home/imas/cert

  updateprocess:
    image: catalogqt/updateprocess
    depends_on:
      - server
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb

  watchdog:
    image: catalogqt/watchdog
    depends_on:
      - server
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/fair4fusion-docker-demo:/docker-entrypoint-properties.d

