version: "3.6"

services:

  db:
    ports:
      - 3306:3306
      - 33060:33060

  server:
    environment:
      - DISABLE_ACCESS_TOKEN=true
      - DEBUG_SPRING_BOOT=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/certs:/home/imas/cert
    ports:
      - 32889:32889

  updateprocess:
    environment:
      - DISABLE_ACCESS_TOKEN=true
      - DEBUG_UPDATE_PROCESS=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
    ports:
      - 32888:32888

  watchdog:
    environment:
      - DISABLE_ACCESS_TOKEN=true
      - DEBUG_IMAS_WATCHDOG=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/fair4fusion-docker-demo:/docker-entrypoint-properties.d
    ports:
      - 32887:32887

